//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyIT.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyIT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odpowiedz powinna byc pusta.
        /// </summary>
        internal static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odpowiedz jest pusta.
        /// </summary>
        internal static string AnswerIsEmpty {
            get {
                return ResourceManager.GetString("AnswerIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odpowiedz nie zawiera tekstu.
        /// </summary>
        internal static string AnswerWithoutContent {
            get {
                return ResourceManager.GetString("AnswerWithoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odpowiedz nie ma przypisanego pytania.
        /// </summary>
        internal static string AnswerWithoutQuestio {
            get {
                return ResourceManager.GetString("AnswerWithoutQuestio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przypisanie poprawne.
        /// </summary>
        internal static string AssignCorrect {
            get {
                return ResourceManager.GetString("AssignCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiana nazwy powiodła sie.
        /// </summary>
        internal static string ChangedName {
            get {
                return ResourceManager.GetString("ChangedName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poprawna walidacja daty.
        /// </summary>
        internal static string CorrectDataValidation {
            get {
                return ResourceManager.GetString("CorrectDataValidation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Walidacja poprawna.
        /// </summary>
        internal static string CorrectValidation {
            get {
                return ResourceManager.GetString("CorrectValidation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyslnie stworzono ankiete.
        /// </summary>
        internal static string CreateSurvey {
            get {
                return ResourceManager.GetString("CreateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie dane są poprawne.
        /// </summary>
        internal static string DataCorrect {
            get {
                return ResourceManager.GetString("DataCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ten adres e-mail jest już przypisany do innego konta.
        /// </summary>
        internal static string EmailIsUsed {
            get {
                return ResourceManager.GetString("EmailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd wyswietlania.
        /// </summary>
        internal static string ErrorDisplay {
            get {
                return ResourceManager.GetString("ErrorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blad wysylania.
        /// </summary>
        internal static string ErrorSend {
            get {
                return ResourceManager.GetString("ErrorSend", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd walidacji.
        /// </summary>
        internal static string ErrorValidation {
            get {
                return ResourceManager.GetString("ErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bledna walidacja odpowiedzi.
        /// </summary>
        internal static string ErrorValidationAnswers {
            get {
                return ResourceManager.GetString("ErrorValidationAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyslnie zapisano ankiete.
        /// </summary>
        internal static string FillSurvey {
            get {
                return ResourceManager.GetString("FillSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyslnie dodano grupe.
        /// </summary>
        internal static string GroupAdded {
            get {
                return ResourceManager.GetString("GroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunieto grupe.
        /// </summary>
        internal static string GroupDeleted {
            get {
                return ResourceManager.GetString("GroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grupa o takiej nazwie istnieje.
        /// </summary>
        internal static string GroupNameUsed {
            get {
                return ResourceManager.GetString("GroupNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grupa nie istnieje.
        /// </summary>
        internal static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ten login jest zajęty.
        /// </summary>
        internal static string LoginIsUsed {
            get {
                return ResourceManager.GetString("LoginIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie wszystkie obiekty istnieja.
        /// </summary>
        internal static string NoDataExist {
            get {
                return ResourceManager.GetString("NoDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak obiektow do przypisania.
        /// </summary>
        internal static string NoDataToAssign {
            get {
                return ResourceManager.GetString("NoDataToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie podano maila.
        /// </summary>
        internal static string NoMail {
            get {
                return ResourceManager.GetString("NoMail", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data rozpoczecia jest wieksza niz data zakonczenia.
        /// </summary>
        internal static string NotValidData1 {
            get {
                return ResourceManager.GetString("NotValidData1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data rozpoczecia musi byc wieksza badz od aktualnej.
        /// </summary>
        internal static string NotValidData2 {
            get {
                return ResourceManager.GetString("NotValidData2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa powinna zaczynać się od wielkiej litery.
        /// </summary>
        internal static string NotValidName {
            get {
                return ResourceManager.GetString("NotValidName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pytanie nie zawiera odpowiedzi.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pytanie nie ma tresci.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyslano.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Za krótka nazwa.
        /// </summary>
        internal static string ShortGroupName {
            get {
                return ResourceManager.GetString("ShortGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło musi zawierać min 6 znakow.
        /// </summary>
        internal static string ShortPass {
            get {
                return ResourceManager.GetString("ShortPass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ankieta o takiej nazwie juz istnieje.
        /// </summary>
        internal static string SurveyNameUsed {
            get {
                return ResourceManager.GetString("SurveyNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Taka ankieta nie istnieje.
        /// </summary>
        internal static string SurveyNotExist {
            get {
                return ResourceManager.GetString("SurveyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ankieta nie zawiera pytan.
        /// </summary>
        internal static string SurveyWithoutQuestions {
            get {
                return ResourceManager.GetString("SurveyWithoutQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odprzypisanie poprawne.
        /// </summary>
        internal static string UnAssignCorrect {
            get {
                return ResourceManager.GetString("UnAssignCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd podczas update&apos;owania danych użytkownika.
        /// </summary>
        internal static string UpdateNameError {
            get {
                return ResourceManager.GetString("UpdateNameError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie zidentyfikowano uzytkownika.
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
